### ISSUE TITLE
Leading zeros on `Quantity` values are not trimmed.

### ISSUE THREAD

**Issue by gakonst** [gakonst/ethers-rs#1279]
# Problem

See the Foundry issue for motivation & proposed solution: https://github.com/foundry-rs/foundry/issues/1590

**Comment by mattsse** [comment]
this happens in

https://github.com/gakonst/ethers-rs/blob/916e9a73341fab3b326be6ddb6fcd61550c8fc7f/ethers-providers/src/lib.rs#L471

due to the `H256` which formats padded

https://github.com/gakonst/ethers-rs/blob/916e9a73341fab3b326be6ddb6fcd61550c8fc7f/ethers-providers/src/provider.rs#L734

but the `location` in `eth_storage_at` is a Quantity number according to the spec, I guess we can simply convert it to a U256 first?
