### ISSUE TITLE
Missing CHANGELOG

### ISSUE THREAD

**Issue by paulrberg** [gakonst/ethers-rs#164]
This library has been recently upgraded from v0.1.3 to 0.2.0, which introduced quite a few breaking changes (such as [the NonceManager now being NonceManagerMiddleware](https://www.diffchecker.com/ixAkzD0i)).

It would be nice if there was a CHANGELOG.md file documenting (at least) the high-level changes.

**Comment by gakonst** [comment]
That's a good point - I unfortunately made quite a few changes since the previous release because I was still exploring how I'd like the library to look like (e.g. the middleware stuff). As a result, I wasn't too diligent with keeping a changelog across releases. 

Do you have any recommendation for an automatic changelog generator? It'd be nice if release/changelogs could be fully automated in CI when there's a `release` PR

**Comment by paulrberg** [comment]
> Do you have any recommendation for an automatic changelog generator?

I fiddled with [semantic-release/changelog](https://github.com/semantic-release/changelog) but I wasn't satisfied. It was too opinionated. Also it has to be added as an npm dependency so that may be out of scope for a Rust project.

What I can recommend though is [keepachangelog.com](https://keepachangelog.com/en/1.0.0/). It does require you to manually keep track of the changes, but their skeleton file does the bulk of the work. The format is nice, simple and logical.
