### ISSUE TITLE
Updating `k256` to `"12.0"`

### ISSUE THREAD

**Issue by xphoniex** [gakonst/ethers-rs#2158]
Currently, `ethers-core` uses version `"0.11"` of `k256` crate. For a separate project (ref https://github.com/RustCrypto/elliptic-curves/issues/754), I went through its changes and decided to help update to `"0.12"` to save others from the trouble. 

However, there's an issue: to get the same signature byte-for-byte, one has to use the new `sign_digest_recoverable` method (instead of `sign_digest`) which returns a tuple of `(sig, recid)`.

Ideally, a new trait `RecoverableSigner` must be created in `signature` crate, instead of [`DigestSigner`](https://docs.rs/signature/latest/signature/trait.DigestSigner.html) and have every wallet use that instead. Some will still have to call methods from `DigestSigner` trait under the hood.

Another approach would be to intercept calls to `self.signer.sign_digest` for local private key wallet, but the problem is that the new `k256::ecdsa::Signature` now lacks `v` component of `r,s,v`. Thus, we have to create another similar struct and return that instead, [here's](https://github.com/gakonst/ethers-rs/blob/69edf3b49e98ff70b7e73bf65510a75fc77baace/ethers-signers/src/wallet/mod.rs#L156) where this matters:

```rust
    /// Signs the provided hash.
    pub fn sign_hash(&self, hash: H256) -> Signature {
        let recoverable_sig: RecoverableSignature =
            self.signer.sign_digest(Sha256Proxy::from(hash));

        let v = u8::from(recoverable_sig.recovery_id()) as u64 + 27; // <----
        
        let r_bytes: FieldBytes<Secp256k1> = recoverable_sig.r().into();
        let s_bytes: FieldBytes<Secp256k1> = recoverable_sig.s().into();

        let r = U256::from_big_endian(r_bytes.as_slice());
        let s = U256::from_big_endian(s_bytes.as_slice());

        Signature { r, s, v }
    }
```

`v` was being extracted from signature itself previously, whereas now it's being returned in the second item of tuple (`recid`).

And if we want to change the `sign_digest` trait signature, then it's the same as first solution. (a new trait).

Either way, this is pretty ugly and I wanted some feedback from maintainers before putting more time into this.

**Comment by kayabaNerve** [comment]
k256 is now actually at 0.13, just to note that.

**Comment by agostbiro** [comment]
I had a quick look at this and it seems to me that upgrading to `k256` v0.13 will be very difficult to pull off in a backward compatible manner, because the [`RecoverableSignature`](https://docs.rs/k256/0.11.6/k256/ecdsa/recoverable/struct.Signature.html) type which is in the public interface of the [`Wallet`](https://github.com/gakonst/ethers-rs/blob/72428503cfb0855579d47f691b48b2d65ad8195b/ethers-signers/src/wallet/mod.rs#L67) `ethers` type  has been removed from `k256`.

Since `ethers` has had a stable release, the preferable solution would be I think if the `k256` crate reintroduced the [`RecoverableSignature`](https://docs.rs/k256/0.11.6/k256/ecdsa/recoverable/struct.Signature.html) type (without rolling back the updated interfaces). Wdyt @tarcieri, is this feasible? I'm happy to do a PR.

**Comment by tarcieri** [comment]
@agostbiro having any types from a pre-1.0 dependency in the public API of a post-1.0 dependency seems like a big problem for `ethers` in general.

It means you can't upgrade from `k256` v0.11 without it being breaking, because even if we reintroduced the `RecoverableSignature` type in a newer release of `k256` v0.11 it would still be treated as a different type by Rust's type system.

I would suggest vendoring `RecoverableSignature` into `ethers`. Note however that if anyone expects it to be the same as `k256::ecdsa::recoverable::Signature` (from `k256` v0.11) that's still a breaking change, but it's probably the best you can do.

**Comment by tarcieri** [comment]
Also I'm happy to attempt this update in `ethers`. It's going to be a bit tricky, and `ethers` is using a number of workarounds for things there didn't used to be first-class APIs for which it would be good to remove.

Note the MSRV bump for the latest release though: 1.65.

**Comment by agostbiro** [comment]
Thanks for the quick answer @tarcieri ! 

Good point that with major version `0.x` all upgrades to `k256` are going to be breaking changes anyway. With this mind, I agree that the best solution is vendoring `RecoverableSignature`.

Let me know if you want to collaborate on landing the upgrade – I've just upgraded to `k256` v0.13 for a custom `ethers` signer middleware in my own repo.

**Comment by tarcieri** [comment]
Here's one prerequisite: https://github.com/sigp/enr/pull/22

**Comment by gakonst** [comment]
We also need to bump it here https://github.com/summa-tx/bitcoins-rs/blob/023f925e99790f6ad87f807176c46e1e8687b442/bip32/Cargo.toml#L20

**Comment by DaniPopes** [comment]
All dependencies have been updated to their latest version
